travis:
  secure:
    BINSTAR_TOKEN: A+2wMF31/x4jgdTHT7GyXdPJcr208ZiSSiIl76c7VsurarL/101Kq9Fo7+FqiaxWRdbbbs3OHdMxPwYW5A34yNJc59brGMgYSEfrfLJ7bpyRGBJY6w+OeVxquafwopxK8iKaxSQycVbxtkVOI7LKpcHJugUx5kim93uDH+P76hbkUI/Wn3r8nLBkvCoYfpM+OEtyCfTEl0zrwmJNpW9wyFF8wRUwHAYLkjpvePIOCT/vyXnyHZUh3ReJK6W58hUVIv/JIF4CAiLLmLEiEHzj0dT2qUx3JQ3NOxteRCI/ao9GLC/Zb7kHUDnvStMHX/jUkSU7hclc1IGb6/Q4sLGGa45TTJj9IRavjsyVtUnjNghUQ1fT8t8N8Ol/dATmITdDKkUzHQtXmP9YcY5VpvCSVyTheMxDWUEHv9+9l3bl5FaGWGHtPs1q9LI6RA/ZUQWfLLfxzd8W55bjnQzEah7js7sy7nJgSFiZBu1ebtvpssX/139S4AQjxdVQAcZn5ItjiDMrnXo+XNPGj7xxBzTpgTGjMDSVdNcsrd0tX8BMTjg5yIyimPhefH479Sj90l/YbTZI0fivt2A8AXhfa4ptDZbSDR8MQ/Dv/9cwy/VaSWffYy+L1W8ON0NZCdw77bBj4N5fGs/7nrhhBPeRFVdeQWlAfIQH71bv1qpDr1mgwvc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
